spring.application.name=back-regalos

# ===============================
# Configuración Base de Datos (PostgreSQL en Supabase)
# ===============================
spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.guzrecbpdrrjzinxjdkk
spring.datasource.password=qOKBGShBL9ElVob1
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# Configuración JPA / Hibernate
# ===============================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Lo dejamos en "none" porque tú creaste y estructuraste manualmente la base de datos con el archivo de la arquitectura SQL. Si lo pusiéramos en "update" o "create", Spring crearía las tablas por su cuenta.
spring.jpa.hibernate.ddl-auto=none

# Especificamos el dialecto
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# Configuración LIMITADA de HikariCP (Para Tier Gratuito de Render - Máx 2 conexiones totales)
# ===============================
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.max-lifetime=30000
spring.datasource.hikari.connection-timeout=5000

# ===============================
# Configuración Seguridad y JWT
# ===============================
jwt.secret=MI_LLAVE_SECRETA_SUPER_SEGURA_PARA_EL_GIFT_STORE_2026
jwt.expiration_hours=8

# ===============================
# Configuración de Swagger / OpenApi
# ===============================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha
